DNS_url:
    # "https://cloudflare-dns.com/dns-query?dns=" # not working in iran ip blocked
    # "https://dns.google/dns-query?dns=" # not working in iran ip blocked
    # "https://doh.opendns.com/dns-query?dns=" # not working in iran ip blocked
    # "https://secure.avastdns.com/dns-query?dns=" # not working in iran ip blocked
    # "https://doh.libredns.gr/dns-query?dns=" # not working in iran ip blocked
    "https://dns.electrotm.org/dns-query?dns="
    # "https://dns.bitdefender.net/dns-query?dns="
    # "https://cluster-1.gac.edu/dns-query?dns="

offline_DNS:
    # DNS over HTTPS IP Address (leave it intact it must Exist)
    DoH:
        "cloudflare-dns.com": "1.1.1.1" # not working in iran  ip blocked
        "dns.google": "8.8.8.8" # not working in iran  ip blocked
        "doh.opendns.com": "208.67.222.222" # not working in iran  ip blocked
        "secure.avastdns.com": "185.185.133.66" # not working in iran  ip blocked
        "doh.libredns.gr": "116.202.176.26" # not working in iran  ip blocked    
        "dns.electrotm.org": "78.157.42.100"
        "dns.bitdefender.net": "34.84.232.67"
        "cluster-1.gac.edu": "138.236.128.101"

    # working pack 
    working_pack:
        "ocsp.pki.goog": "172.217.16.195"
        "googleads.g.doubleclick.net": "45.157.177.108"
        "fonts.gstatic.com": "142.250.185.227"
        "rr2---sn-vh5ouxa-hju6.googlevideo.com": "213.202.6.141"
        "jnn-pa.googleapis.com": "45.157.177.108"
        "static.doubleclick.net": "202.61.195.218" 
        "rr4---sn-hju7en7k.googlevideo.com": "74.125.167.74"
        "rr1---sn-hju7en7r.googlevideo.com": "74.125.167.87"
        "play.google.com": "142.250.184.238"
        "rr3---sn-vh5ouxa-hjuz.googlevideo.com": "134.0.218.206" 
        "rr3---sn-hju7enel.googlevideo.com": "74.125.98.40"
        "download.visualstudio.microsoft.com": "68.232.34.200"
        "rr2---sn-hju7enel.googlevideo.com": "74.125.98.39"
        "rr2---sn-hju7en7k.googlevideo.com": "74.125.167.72" 
        "rr3---sn-4g5lznl6.googlevideo.com": "74.125.173.40" 
        "rr3---sn-hju7en7k.googlevideo.com": "74.125.167.73"
        "rr1---sn-hju7enll.googlevideo.com": "74.125.98.6"
        "rr6---sn-hju7en7r.googlevideo.com": "74.125.167.92"
        "www.gstatic.com": "142.250.185.99" 
        "apis.google.com": "172.217.23.110"
        "adservice.google.com": "202.61.195.218"
        "mail.google.com": "142.250.186.37" 
        "accounts.google.com": "172.217.16.205" 
        "lh3.googleusercontent.com": "193.26.157.66"
        "accounts.youtube.com": "172.217.16.206"
        "ssl.gstatic.com": "142.250.184.195" 
        "rr4---sn-hju7enll.googlevideo.com": "74.125.98.9"
        "rr2---sn-hju7enll.googlevideo.com": "74.125.98.7"
        "rr1---sn-hju7enel.googlevideo.com": "74.125.98.38"
        "rr5---sn-vh5ouxa-hjuz.googlevideo.com": "134.0.218.208" 
        "i1.ytimg.com": "172.217.18.14"
        "plos.org": "162.159.135.42" 
        "fonts.googleapis.com": "89.58.57.45"
        "genweb.plos.org": "104.26.1.141"
        "static.ads-twitter.com": "146.75.120.157"
        "www.google-analytics.com": "142.250.185.174"
        "rr1---sn-vh5ouxa-hju6.googlevideo.com": "213.202.6.140"
        "rr5---sn-vh5ouxa-hju6.googlevideo.com": "213.202.6.144"
        "rr5---sn-nv47zn7y.googlevideo.com": "173.194.15.74" 
        "safebrowsing.googleapis.com": "202.61.195.218"
        "rr4---sn-vh5ouxa-hju6.googlevideo.com": "213.202.6.143"
        "rr4---sn-hju7en7r.googlevideo.com": "74.125.167.90"
        "r1---sn-hju7enel.googlevideo.com": "74.125.98.38" 
        "rr1---sn-nv47zn7r.googlevideo.com": "173.194.15.38"
        "rr2---sn-vh5ouxa-hjuz.googlevideo.com": "134.0.218.205" 
        "rr4---sn-nv47zn7r.googlevideo.com": "173.194.15.41"

        "www.google.com": "142.250.186.36"
        # "www.google.com": "216.239.38.120"
        "youtube.com": "216.239.38.120"
        "youtu.be": "216.239.38.120"
        "www.youtube.com": "216.239.38.120"
        "i.ytimg.com": "216.239.38.120"

        # "yt3.ggpht.com": "64.233.165.198" # filtered
        # "yt3.ggpht.com": "142.250.179.161" # filtered
        # "yt3.ggpht.com": "142.250.186.65" # sometimes work
        "yt3.ggpht.com": "142.250.186.36" # most of times work