DNS_url:
    "https://cloudflare-dns.com/dns-query?dns="
    # "https://8.8.4.4/dns-query?dns=" # blocked?
    # "https://8.8.8.8/dns-query?dns=" # blocked?
    # "https://1.1.1.1/dns-query?dns=" # blocked?
    # "https://dns.google/dns-query?dns=" # blocked?
    # "https://doh.opendns.com/dns-query?dns=" # blocked?
    # "https://secure.avastdns.com/dns-query?dns=" # blocked?
    # "https://doh.libredns.gr/dns-query?dns=" # blocked?
    # "https://dns.electrotm.org/dns-query?dns=" # DNS server inside iran
    # "https://dns.bitdefender.net/dns-query?dns="
    # "https://cluster-1.gac.edu/dns-query?dns="

offline_DNS:
    # DNS over HTTPS IP Address (leave it intact, it must Exist)
    DoH:
        # "cloudflare-dns.com": "1.1.1.1" # IP filtered
        # "cloudflare-dns.com": "172.67.128.43" # any cloudflare ip can be used for cloudflare DoH
        # "cloudflare-dns.com": "64.68.192.137"
        "dns.google": "8.8.8.8" # IP filtered
        "doh.opendns.com": "208.67.222.222"
        "secure.avastdns.com": "185.185.133.66"
        "doh.libredns.gr": "116.202.176.26"
        "dns.electrotm.org": "78.157.42.100"
        "dns.bitdefender.net": "34.84.232.67"
        "cluster-1.gac.edu": "138.236.128.101"

    # twitter working pack 
    twitter:
        # "ocsp.digicert.com": "192.229.211.108"
        "api.twitter.com": "104.244.42.66"
        "twitter.com": "104.244.42.1"
        "pbs.twimg.com": "93.184.220.70"
        "abs-0.twimg.com": "104.244.43.131"
        "abs.twimg.com": "152.199.24.185"
        "video.twimg.com": "192.229.220.133"
        "t.co": "104.244.42.69"
        "ton.local.twitter.com": "104.244.42.1"

    # Instagram whatsapp facebook working pack
    mata:
        "instagram.com": "163.70.128.174"
        "www.instagram.com": "163.70.128.174"
        "static.cdninstagram.com": "163.70.132.63"
        "scontent.cdninstagram.com": "163.70.132.63"
        "privacycenter.instagram.com": "163.70.128.174"
        "help.instagram.com": "163.70.128.174"
        "l.instagram.com": "163.70.128.174"
        "e1.whatsapp.net": "163.70.128.60"
        "e2.whatsapp.net": "163.70.128.60"
        "e3.whatsapp.net": "163.70.128.60"
        "e4.whatsapp.net": "163.70.128.60"
        "e5.whatsapp.net": "163.70.128.60"
        "e6.whatsapp.net": "163.70.128.60"
        "e7.whatsapp.net": "163.70.128.60"
        "e8.whatsapp.net": "163.70.128.60"
        "e9.whatsapp.net": "163.70.128.60"
        "e10.whatsapp.net": "163.70.128.60"
        "e11.whatsapp.net": "163.70.128.60"
        "e12.whatsapp.net": "163.70.128.60"
        "e13.whatsapp.net": "163.70.128.60"
        "e14.whatsapp.net": "163.70.128.60"
        "e15.whatsapp.net": "163.70.128.60"
        "e16.whatsapp.net": "163.70.128.60"
        "dit.whatsapp.net": "185.60.219.60"
        "g.whatsapp.net": "185.60.218.54"
        "wa.me": "185.60.219.60"
        "web.whatsapp.com": "31.13.83.51"
        "whatsapp.net": "31.13.83.51"
        "whatsapp.com": "31.13.83.51"
        "cdn.whatsapp.net": "31.13.83.51"
        "snr.whatsapp.net": "31.13.83.51"
        "static.xx.fbcdn.net": "31.13.75.13"
        "scontent-mct1-1.xx.fbcdn.net": "31.13.75.13"
        "video-mct1-1.xx.fbcdn.net": "31.13.75.13"
        "video.fevn1-2.fna.fbcdn.net": "185.48.241.146"
        "video.fevn1-4.fna.fbcdn.net": "185.48.243.145"
        "scontent.xx.fbcdn.net": "185.48.240.146"
        "scontent.fevn1-1.fna.fbcdn.net": "185.48.240.145"
        "scontent.fevn1-2.fna.fbcdn.net": "185.48.241.145"
        "scontent.fevn1-3.fna.fbcdn.net": "185.48.242.146"
        "scontent.fevn1-4.fna.fbcdn.net": "185.48.243.147"
        "connect.facebook.net": "31.13.84.51"
        "facebook.com": "31.13.65.49"
        "developers.facebook.com": "31.13.84.8"
        "about.meta.com": "163.70.128.13"
        "meta.com": "163.70.128.13"

    # GooglePlay working pack
    google_play:

    # Youtube working pack
    youtube:
        "ocsp.pki.goog": "172.217.16.195"
        "googleads.g.doubleclick.net": "45.157.177.108"
        "fonts.gstatic.com": "142.250.185.227"
        "rr2---sn-vh5ouxa-hju6.googlevideo.com": "213.202.6.141"
        "jnn-pa.googleapis.com": "45.157.177.108"
        "static.doubleclick.net": "202.61.195.218"
        "rr4---sn-hju7en7k.googlevideo.com": "74.125.167.74"
        "rr1---sn-hju7en7r.googlevideo.com": "74.125.167.87"
        "play.google.com": "142.250.184.238"
        "rr3---sn-vh5ouxa-hjuz.googlevideo.com": "134.0.218.206"
        "rr3---sn-hju7enel.googlevideo.com": "74.125.98.40"
        "download.visualstudio.microsoft.com": "68.232.34.200"
        "i.ytimg.com": "142.250.186.150"
        "rr2---sn-hju7enel.googlevideo.com": "74.125.98.39"
        "rr2---sn-hju7en7k.googlevideo.com": "74.125.167.72"
        "rr3---sn-4g5lznl6.googlevideo.com": "74.125.173.40"
        "rr3---sn-hju7en7k.googlevideo.com": "74.125.167.73"
        "rr1---sn-hju7enll.googlevideo.com": "74.125.98.6"
        "rr6---sn-hju7en7r.googlevideo.com": "74.125.167.92"
        "www.gstatic.com": "142.250.185.99"
        "apis.google.com": "172.217.23.110"
        "adservice.google.com": "202.61.195.218"
        "mail.google.com": "142.250.186.37"
        "accounts.google.com": "172.217.16.205"
        "lh3.googleusercontent.com": "193.26.157.66"
        "accounts.youtube.com": "172.217.16.206"
        "ssl.gstatic.com": "142.250.184.195"
        "rr4---sn-hju7enll.googlevideo.com": "74.125.98.9"
        "rr2---sn-hju7enll.googlevideo.com": "74.125.98.7"
        "rr1---sn-hju7enel.googlevideo.com": "74.125.98.38"
        "rr5---sn-vh5ouxa-hjuz.googlevideo.com": "134.0.218.208"
        "i1.ytimg.com": "172.217.18.14"
        "plos.org": "162.159.135.42"
        "fonts.googleapis.com": "89.58.57.45"
        "genweb.plos.org": "104.26.1.141"
        "static.ads-twitter.com": "146.75.120.157"
        "www.google-analytics.com": "142.250.185.174"
        "rr1---sn-vh5ouxa-hju6.googlevideo.com": "213.202.6.140"
        "rr5---sn-vh5ouxa-hju6.googlevideo.com": "213.202.6.144"
        "rr5---sn-nv47zn7y.googlevideo.com": "173.194.15.74"
        "safebrowsing.googleapis.com": "202.61.195.218"
        "rr4---sn-vh5ouxa-hju6.googlevideo.com": "213.202.6.143"
        "rr4---sn-hju7en7r.googlevideo.com": "74.125.167.90"
        "r1---sn-hju7enel.googlevideo.com": "74.125.98.38"
        "rr1---sn-nv47zn7r.googlevideo.com": "173.194.15.38"
        "rr2---sn-vh5ouxa-hjuz.googlevideo.com": "134.0.218.205"
        "rr4---sn-nv47zn7r.googlevideo.com": "173.194.15.41"
        "www.google.com": "142.250.186.36"
        # "www.google.com": "216.239.38.120"
        "youtube.com": "216.239.38.120"
        "youtu.be": "216.239.38.120"
        "www.youtube.com": "216.239.38.120"
        # "yt3.ggpht.com": "64.233.165.198"   # filtered
        # "yt3.ggpht.com": "142.250.179.161"  # filtered
        # "yt3.ggpht.com": "142.250.186.65"   # sometimes work
        "yt3.ggpht.com": "142.250.186.36"  # most of times work